name: Run OTT Ranking Bot

on:
  schedule:
    # 🚨 전 세계 봇 출근 시간(정각)을 피해서 오전 8시 17분으로 꼼수 세팅! (UTC 23:17)
    - cron: '17 23 * * *'
  
  # GitHub 페이지에서 'Run workflow' 버튼으로 수동 실행 가능
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Node.js 24버전 노란색 경고창 해결
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # [경고 해결] v3 -> v4 로 업데이트

      - name: Set up Python
        uses: actions/setup-python@v5  # [경고 해결] v4 -> v5 로 업데이트
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 중복된 줄을 하나로 깔끔하게 합쳤습니다!
          pip install requests beautifulsoup4 cloudscraper

      - name: Run script
        env:
          # Settings > Secrets and variables > Actions에 등록된 변수 사용
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
